---

- name: "Delete default nginx"
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: "Configure nginx"
  template: src=/Templates/nginx/default dest=/etc/nginx/sites-enabled/default

