---

- name: Install packages certbot
  apt:
    state: latest
    pkg:
      - certbot
    update_cache: yes

- name: Setup cron for weekly cert renew
  cron:
    name: certbot renew
    minute: 20
    hour: 2
    weekday: 0
    job: "certbot renew --renew-hook 'systemctl reload dovecot; systemctl reload postfix' --quiet"

- name: Check whether the cert exists
  stat:
    path: /etc/letsencrypt/live/mail.juraev72.ru/fullchain.pem
  register: live_cert

- name: Generate certificates
  shell: certbot certonly --standalone --rsa-key-size 4096 -d mail.juraev72.ru -d imap.juraev72.ru -d smtp.juraev72.ru -m test@juraev72.ru --agree-tos
  when: live_cert.stat.exists == False
